apiVersion: v1
kind: Namespace
metadata:
   name: local-service
   labels:
     name: local-service
---
apiVersion: v1
kind: Service
metadata:
  name: s88
  namespace: local-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
    - protocol: TCP
      name: es
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: minio
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: robot
      port: 8090
      targetPort: 8090
    - protocol: TCP
      name: robot-wiki
      port: 1026
      targetPort: 1026
    - protocol: TCP
      name: redis1
      port: 7001
      targetPort: 7001
    - protocol: TCP
      name: redis2
      port: 7002
      targetPort: 7002
    - protocol: TCP
      name: redis3
      port: 7003
      targetPort: 7003
    - protocol: TCP
      name: redis4
      port: 7004
      targetPort: 7004
    - protocol: TCP
      name: redis5
      port: 7005
      targetPort: 7005
    - protocol: TCP
      name: redis6
      port: 7006
      targetPort: 7006
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: local-service
  name: s88
subsets:
  - addresses:
      - ip: 192.168.1.88
    ports:
      - port: 3306
        name: mysql
      - port: 9200
        name: es
      - port: 8090
        name: robot
      - port: 1026
        name: robot-wiki
      - port: 9000
        name: minio
      - port: 7001
        name: redis1
      - port: 7002
        name: redis2
      - port: 7003
        name: redis3
      - port: 7004
        name: redis4
      - port: 7005
        name: redis5
      - port: 7006
        name: redis6
---
apiVersion: v1
kind: Service
metadata:
  name: s98
  namespace: local-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: local-service
  name: s98
subsets:
  - addresses:
      - ip: 192.168.1.98
    ports:
      - port: 3306
        name: mysql
