apiVersion: v1
kind: Secret
metadata:
  name: csi-driver-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: "testtest"
  secretAccessKey: "testtest"
  endpoint: http://s88.local-service:9000
  region: ""
